import { BlobState, Status } from '../types';
import { Group } from "../types";
import { editors } from '../utils/editors';

export const baseLayout: BlobState[] = [
  {
    group: Group.KNOW,
    id: 'sources',
    title: 'Data Sources',
    description: 'Name/describe your project’s key data sources, whether you’re collecting data yourself or accessing via third parties.',
    editor: editors['sources'],
    row: 0,
    column: 0,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.KNOW,
    id: 'rights',
    title: 'Rights around data sources',
    description: 'Where did you get the data from? Is it produced by an organisation or collected directly from individuals?',
    editor: editors['rights'],
    row: 0,
    column: 1,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.KNOW,
    id: 'limitations',
    title: 'Limitations in data sources',
    description: 'Are there limitations that could influence your project’s outcomes?',
    editor: editors['limitations'],
    row: 0,
    column: 2,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.KNOW,
    id: 'ethical-legislative',
    title: 'Ethical and legislative context',
    description: 'What existing ethical codes apply to your sector or project? What legislation, policies, or other regulation shape how you use data?',
    editor: editors['ethical-legislative'],
    row: 0,
    column: 3,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.EXPLORE,
    id: 'reasons',
    title: 'Your reason for using data',
    description: 'What is your primary purpose for collecting and using data in this project?',
    editor: editors['reasons'],
    row: 1,
    column: 0,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.EXPLORE,
    id: 'positive-effects',
    title: 'Positive effects on people',
    description: 'Which individuals, groups, demographics or organisations will be positively affected by this project? How?',
    editor: editors['positive-effects'],
    row: 1,
    column: 1,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.EXPLORE,
    id: 'negative-effects',
    title: 'Negative effects on people',
    description: 'Who could be negatively affected by this project?',
    editor: editors['negative-effects'],
    row: 1,
    column: 2,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.EXPLORE,
    id: 'mitigations',
    title: 'Minimising negative effects',
    description: 'What steps can you take to minimise harm?',
    editor: editors['mitigations'],
    row: 1,
    column: 3,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.PLAN,
    id: 'engaging',
    title: 'Engaging with people',
    description: 'How can people engage with you about the project?',
    editor: editors['engaging'],
    row: 2,
    column: 0,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.PLAN,
    id: 'communicating',
    title: 'Communicating your purpose',
    description: 'Do people understand your purpose – especially people whom the data is about or who are impacted by its use?',
    editor: editors['communicating'],
    row: 2,
    column: 1,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.PLAN,
    id: 'openness',
    title: 'Openness and transparency',
    description: 'How open can you be about this project? Could you publish your methodology, metadata, datasets, code or impact measurements?',
    editor: editors['openness'],
    row: 2,
    column: 2,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.PLAN,
    id: 'sharing',
    title: 'Sharing data with others',
    description: 'Are you going to be sharing data with other organisations? If so, who?',
    editor: editors['sharing'],
    row: 2,
    column: 3,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.INTEGRATE,
    id: 'implementation',
    title: 'Ongoing implementation',
    description: 'Are you routinely building in thoughts, ideas and considerations of people affected by your project? How?',
    editor: editors['implementation'],
    row: 0,
    column: 4,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.INTEGRATE,
    id: 'review',
    title: 'Reviews and iterations',
    description: 'How will ongoing data ethics issues be measured, monitored, discussed and actioned?',
    editor: editors['review'],
    row: 1,
    column: 4,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
  {
    group: Group.INTEGRATE,
    id: 'actions',
    title: 'Your actions',
    description: 'What actions will you take before moving forward with this project? Which should take priority?',
    editor: editors['actions'],
    row: 2,
    column: 4,
    status: Status.IN_PROGRESS,
    content: null,
    notes: null,
  },
];
